apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-story-lab
  namespace: k8s-lab
  labels:
    app: k8s-story-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-story-lab
  template:
    metadata:
      labels:
        app: k8s-story-lab
    spec:
      containers:
        - name: k8s-story-lab
          image: elroymalayov/k8s-lab:belshy-v2
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
