apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: k8s-story-lab
  namespace: k8s-lab
  labels:
    app: k8s-story-lab
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-story-lab
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
